### ISSUE TITLE
Allow Spring 6 to be used with ml-gradle

### ISSUE THREAD

**Issue by rjdew-progress** [marklogic/ml-gradle#719]
A project that wishes to use Spring 6 will encounter errors due to functions that were removed in Spring 6.

I'll provide a PR.

**To Reproduce**
1. Create a new ml-gradle project
2. Add Spring 6 dependency
3. Set Spring 6 constraints
4. Deploy the application and errors will be encountered with deployment

**Expected behavior**
Be able to deploy with Spring 6 without encountering errors.

**Comment by rjrudin** [comment]
I verified that the issue is due to `ResponseEntity::getStatusCode` returning a different type between Spring 5 and Spring 6. Same goes for `HttpStatusCodeException::getStatusCode`. So when both Spring 5 and Spring 6 dependencies are on the classpath, Gradle chooses Spring 6 for ml-gradle to use, and it gets back a type it's not expecting.
